"""hhuser btaddr

Revision ID: 161ae99f80a2
Revises: 47fecba5992e
Create Date: 2015-12-12 22:49:29.287142

"""

# revision identifiers, used by Alembic.
revision = '161ae99f80a2'
down_revision = '47fecba5992e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
