"""add users

Revision ID: 47fecba5992e
Revises: aed18b0e709
Create Date: 2015-12-10 05:04:41.628173

"""

# revision identifiers, used by Alembic.
revision = '47fecba5992e'
down_revision = 'aed18b0e709'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('evtype', sa.Integer(), nullable=True))
    op.drop_constraint(u'event_type_fkey', 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'event_type', ['evtype'], ['id'])
    op.drop_column('event', 'type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key(u'event_type_fkey', 'event', 'event_type', ['type'], ['id'])
    op.drop_column('event', 'evtype')
    ### end Alembic commands ###
