"""hhuser btaddr fix

Revision ID: 547c800f9fb6
Revises: 161ae99f80a2
Create Date: 2015-12-12 23:47:47.298254

"""

# revision identifiers, used by Alembic.
revision = '547c800f9fb6'
down_revision = '161ae99f80a2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
